More core sdk examples
immutable/imx-core-sdk pull request #257
Opened 2023-01-25 19:52 UTC by cdrabner95

# Summary

Adds examples to the core-sdk for functionality with withdrawals, transfers, balances, users, and projects.

# Why the changes

Support team's project to flesh out all core-sdk code examples.

# Before merging
- [ ] ***For Immutable developers:*** Do the changes in this PR require documentation updates? Please refer to this [SDK documentation guide](https://immutable.atlassian.net/wiki/spaces/PPS/pages/1916994017/SDK+documentation+guide) and list links to documentation update PRs (they don't have to be merged) below (or write `N/A`):

2023-01-30 23:00 UTC, sprngbk requested changes

2023-01-31 19:31 UTC, cdrabner95 commented on examples/README.md
> +## Get Balance
fixed

2023-01-31 19:42 UTC, cdrabner95 commented on examples/completeErc20Withdrawal.ts
> +
done

2023-01-31 19:42 UTC, cdrabner95 commented on examples/getProjects.ts
> +
done

2023-02-01 04:14 UTC, CodeSchwert commented on examples/listWithdrawals.ts
> +
Extra lines here

2023-02-01 05:25 UTC, CodeSchwert approved these changes

2023-02-01 05:27 UTC, Nathan-Ballantyne approved these changes

2023-02-01 05:32 UTC, merged